apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets
  namespace: codereviewer

spec:
  provider: azure

  secretObjects:
    - secretName: kv-secret
      type: Opaque
      data:
        - objectName: AZURE_OPENAI_API_KEY
          key: AZURE_OPENAI_API_KEY

        - objectName: DATABASE_URL
          key: DATABASE_URL

        - objectName: JWT_SECRET
          key: JWT_SECRET

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"

    userAssignedIdentityID: "4f984e18-c8c3-473e-8098-76390467c02b"

    keyvaultName: "coderaptor-prod-h476d-kv"

    tenantId: "e3d774dc-b8bb-4368-987e-c4738a1b89e1"

    objects: |
      array:
        - |
          objectName: AZUREOPENAIAPIKEY
          objectType: secret
          objectAlias: AZURE_OPENAI_API_KEY

        - |
          objectName: DATABASEURL
          objectType: secret
          objectAlias: DATABASE_URL

        - |
          objectName: JWT
          objectType: secret
          objectAlias: JWT_SECRET
